baseURL = "/"
languageCode = 'ja'
title = 'd.sk85.org'
theme = 'minimal'
enableGitInfo = true
publishDir = "/Users/shuhei/hugo"

[outputs]
  home = ["HTML", "JSON"]

[params]
  imgresourceserver = "https://img.sk85.org/imaginary/resize?"
  enable_search = true
  searchserver_url = "/search/"
  rss_base_url = 'https://d.sk85.org'

[permalinks]
  posts = "/:sections/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  archive = "archives"
  nnn = "n年日記"
  
  
[menu]
  [[menu.main]]
    identifier = "search"
    name = "search"
    title = "search"
    url = "/search/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags/"
    weight = 3
    
  [[menu.main]]
    identifier = "archives"
    name = "archives"
    title = "archives"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "top"
    name = "top"
    title = "top"
    url = "/"
    weight = 1
